apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-engineering
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/Abiamahladi/platform-engineering.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
