apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: employee-db-secret
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: employee-db
  destination:
    name: employee-db-secret
    create: true
  vaultAuthRef: vault-auth
  refreshAfter: 30s
